export default {
  windowEl: window,
  documentEl: document,
  htmlEl: document.documentElement,
  bodyEl: document.body,
  navSearchClear: document.querySelectorAll('.nav-search-input'),
  searchClear: document.querySelectorAll('.nav-search-clear'),
  graph: document.querySelector('.graph-visual-box'),
  chart: document.querySelector('.chart-donut-box'),
  graphRadio: document.querySelectorAll('.radio-type'),
  chartRadio: document.querySelectorAll('.chart-type'),
  dropdownBtn: document.querySelectorAll('.btn-dropdown'),
  publishForm: document.querySelector('.publish-form'),
  publishDropdown: document.querySelectorAll('.publish-dropdown'),
  publishDropdownBtn: document.querySelectorAll('.publish-dropdown-btn'),
  publishInput: document.querySelector('.publish-input'),
  publishMaxtext: document.querySelector('.publish-length span'),
  publishSubmit: document.querySelector('.publish-submit'),
  publishReset: document.querySelector('.publish-reset'),
  publishTextarea: document.querySelectorAll('.input:not(.nav-search-input):not(.form-input)'),
  textAreaSettings: document.querySelectorAll('.personal-content'),
  personalAbout: document.querySelector('#personal-about'),
  personalStrategy: document.querySelector('#personal-strategy'),
  apiCheck: document.querySelectorAll('.api-checkbox input'),
  apiBtnNext: document.querySelector('[data-graph-path="add-exchange"]'),
  apiExchangeTitle: document.querySelector('.api-title-exchange'),
  passwordBtns: document.querySelectorAll('.security-password-btn'),
  passwordBtns: document.querySelectorAll('.security-password-btn'),
  qrBtn: document.querySelector('.step-qr-show'),
  headerBtn: document.querySelector('.action-dropdown'),
  notificationItems: document.querySelectorAll('.notification-item'),
  commentArea: document.querySelectorAll('.comment-input'),
  postOpenComments: document.querySelectorAll('.post-comments'),
  postReply: document.querySelectorAll('.btn-reply'),
  passShowHide: document.querySelectorAll('.form-pass'),
  copyPurchases: document.querySelectorAll('.purchases-copy-btn'),
  mobileSearch: document.querySelector('.btn-search'),
  mobileSearchForm: document.querySelector('.nav-search-mobile'),
  investRadioBtn: document.querySelectorAll('.invest-tabs-radio .radio-btn'),
  positionsItemBtn: document.querySelectorAll('.positions-btn'),
  replyShowList: document.querySelectorAll('.post-reply-visible'),
};
